contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # user
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/profile/update/', views.user_update, name='user_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)
    
    def __str__(self):
        return f'{self.name}'


class Contacts(models.Model):

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True, null=True
        )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contacts, Category
from django.core.paginator import Paginator
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation

class ContactsForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite seu nome'
            }
        ),
        label='Primeiro Nome',
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite seu sobrenome'
            }
        ),
        label='Sobrenome',
    )

    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite seu telefone'
            }
        ),
        label='Telefone',
    )

    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs={
                'placeholder': 'Digite seu email'
            }
        ),
        label='Email',
        required=False,
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Digite uma descrição',
                'rows': 5,
                'cols': 20
            }
        ),
        label='Descrição',
        required=False,
    )

    category = forms.ModelChoiceField(
        queryset = Category.objects.all(),
        empty_label = 'Selecione a categoria',
        label='Categoria',
        required=False,
    )

    picture = forms.ImageField(
        label='Foto',
        required=False,
        widget=forms.FileInput(
            attrs = {
                'accept' : 'image/*'
            }
        ),
    )

    class Meta:
        model = Contacts
        fields = ('first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture')
   

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        msg = ValidationError(
                    'Primeiro nome não pode ser igual ao segundo.',
                    code='invalid'
                )

        if first_name == last_name:
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)


        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError('Não digite ABC neste campo.',
                code='invalid')
            )
        return first_name
    
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        label='Primeiro Nome'
    )
    last_name = forms.CharField(
        required=True,
        label='Sobrenome'
    )
    email = forms.EmailField(
        required=True,
        label='Email'
    )
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error('email', ValidationError('Email já cadastrado.', code='invalid'))
        return email
    
class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Obrigatório',
        label='Primeiro Nome',
        error_messages={
            'min_length': 'O primeiro nome deve ter no mínimo 2 caracteres.',
            'max_length': 'O primeiro nome deve ter no máximo 30 caracteres.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Obrigatório',
        label='Sobrenome',
        error_messages={
            'min_length': 'O sobrenome deve ter no mínimo 2 caracteres.',
            'max_length': 'O sobrenome deve ter no máximo 30 caracteres.'
        }
    )
    password1 = forms.CharField(
        label='Senha',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete' : 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )
    password2 = forms.CharField(
        label='Confirmação de Senha',
        widget=forms.PasswordInput(attrs={'autocomplete' : 'new-password'}),
        strip=False,
        help_text='Digite a mesma senha para verificação.',
        required=False,
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',)

    def save(self, commit = True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)
        
        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('As senhas não coincidem.', code='invalid')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if email != current_email:
            if User.objects.filter(email=email).exists():
                self.add_error('email', ValidationError('Email já cadastrado.', code='invalid'))
        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error('password1', errors)

        return password1

contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contacts
from django.core.paginator import Paginator
from django import forms
from contact.forms import ContactsForm, RegisterForm, RegisterUpdateForm
from django.urls import reverse
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    contacts = Contacts.objects.filter(show=True).order_by('id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj" : page_obj,
        "site_title": '- Contatos'
    }
    return render(
        request,
        'contact/index.html',
        context = context
    )

def contact(request, contact_id):
    single_contact = get_object_or_404(Contacts.objects.filter(pk=contact_id, show=True))

    site_title = f' - {single_contact.first_name + ' ' + single_contact.last_name} '

    context = {
        'contact' : single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context = context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contacts.objects.filter(show=True).filter(
        Q(first_name__icontains=search_value) | 
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value) ).order_by('id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj" : page_obj,
        "site_title": '- Busca',
        'search_value': search_value,
    }
    return render(
        request,
        'contact/index.html',
        context = context
    )

@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactsForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,

        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.id)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactsForm(),
        'form_action': form_action
    }

    return render(
        request,
        'contact/create.html',
        context
    )

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(Contacts, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactsForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'form_action': form_action,

        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.id)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactsForm(instance=contact),
        'form_action': form_action
    }

    return render(
        request,
        'contact/create.html',
        context
    )

@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(Contacts, pk=contact_id, show=True)
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(request, 'contact/contact.html', {
        'contact': contact,
        'confirmation' : confirmation, 
    })

def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request=request, message='Usuário cadastrado com sucesso!')
            return redirect('contact:login')

    return render(request,
                  'contact/register.html',
                  {
                      'form' : form,
                  }
                  )

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request=request, message='Login realizado com sucesso!')
            return redirect('contact:index')
        messages.error(request=request, message='Usuário ou senha inválidos.')



    return render(request,
                  'contact/login.html',
                  {
                      'form' : form
                  }
                  )

@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(request,
                    'contact/user_update.html',
                    {
                        'form' : form
                    })
    form = RegisterUpdateForm(data= request.POST, instance=request.user)
    if not form.is_valid():
        return render(request,
                    'contact/user_update.html',
                    {
                        'form' : form
                    })
    form.save()
    messages.success(request=request, message='Perfil atualizado com sucesso!')
    return redirect('contact:user_update')

contact/templates/contact/contact.html
{% extends "global/base.html" %}
{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>

        <p><b>ID:</b> {{ contact.id }}</p>
        <p><b>E-mail:</b> {{ contact.email }}</p>
        <p><b>Telefone:</b> {{ contact.phone }}</p>
        <p><b>Data de Criação:</b> {{ contact.created_date }}</p>
        <p><b>Descrição:</b> {{ contact.description }}</p>
        <p><b>Categoria:</b> {{ contact.category }}</p>
        {% if contact.picture %}
        <p><img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}"></p>
        {% endif %}
        
        {% if user == contact.owner %}
        <div class="contact-links">
            <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Editar</a>
            <form action="{% url "contact:delete" contact.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-link btn-delete" type="submit">Tem certeza que deseja deletar?</button>
                {% else %}
                    <button class="btn btn-link btn-delete" type="submit">Deletar</button>
                {% endif %}
            </form>
        </div>
        {% endif %}


    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">

<h2>Contact</h2>

<form 
action = "{{ form_action }}"
method="POST"
enctype="multipart/form-data"
>
{% csrf_token %}      

<div class="form-content">

{% for field in form %}
<div class="form-group">
<label for="{{ field.id_for_label }}">{{ field.label }}</label>
{{ field }}
{{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
</div>
<div class="form-group">
  {% if field.name == 'picture' and field.value.url %}
      <img src="{{ field.value.url }}" alt="Foto de {{ form.first_name.value }} {{ form.last_name.value }}">
  {% endif %}
</div>
{% endfor %}
</div>

{% if form.non_field_errors %}
<div class="form-content">
<div class="form-group">
<div class="message error">
{{ form.non_field_errors }}
</div>
</div>
</div>
{% endif %}

<div class="form-content">
<div class="form-group">
<button class="btn" type="submit">Send</button>
</div>
</div>

</form>
</div>
{% endblock content%}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contatos
                </caption>
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Nome</th>
                        <th class="table-header">Sobrenome</th>
                        <th class="table-header">Telefone</th>
                        <th class="table-header">E-mail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a href="{% url "contact:contact" contact.id %}" class="table-link">
                                    {{ contact.id }}
                                </a>
                            </td>
                            <td class="table-cel">
                                {{ contact.first_name }}
                            </td>
                            <td class="table-cel">
                                {{ contact.last_name }}
                            </td>
                            <td class="table-cel">
                                {{ contact.phone }}
                            </td>
                            <td class="table-cel">
                                {{ contact.email }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado.
        </h1>
        </div>
    {% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">

<h2>Login</h2>
    {% if user.is_authenticated %}
        <p>Você está logado como {{ user.username }},
            <a href="{% url "contact:logout" %}">Clique aqui para sair</a>
        </p>
    {% else %}
        {% include "contact/partials/user-form.html" %}
    {% endif %}


</div>
{% endblock content%}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">

<h2>Registrar</h2>

{% include "contact/partials/user-form.html" %}
</div>
{% endblock content%}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">

<h2>Atualizar Cadastro</h2>

{% include "contact/partials/user-form.html" %}
</div>
{% endblock content %}